### ISSUE TITLE
AppWage no longer works since Apple closed Autoingestion tool

### ISSUE THREAD

**Issue by neave** [hankinsoft/AppWage#22]
From the error logs in AppWage:

> The Autoingestion tool is no longer available to download your Sales and Trends reports or your Payments and Financial reports. To automate your report downloads, get started with Reporter.
> 
> See https://itunespartner.apple.com/en/apps/news/83091910

I guess this is the end of AppWage?

**Comment by ddaddy** [comment]
Have you tried updating?
This was fixed a while ago.

**Comment by hankinsoft** [comment]
This was fixed in early December, please update.

**Comment by neave** [comment]
Will try to compile latest in Xcode. I was using the version downloaded from the appwage.com homepage which hasn't been updated, I think.

**Comment by hankinsoft** [comment]
Hi,
There is no autoupdate functionality in AppWage, so you would need to redownload from appwage.com. What version do you see in the 'About' screen? The latest website download is: 1.0.101 (605).

**Comment by neave** [comment]
@hankinsoft Thanks for helping, but still no luck. I've redownloaded from appwage.com and now all I get is

```
2016/12/20 13:02:10:333  ITCE: Error downloading report. Error:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
    <Code>108</Code>
    <Message>Invalid username and password. Change values and try again.</Message>
</Error>
2016/12/20 13:02:10:333  ITCE: Failed to download daily report
2016/12/20 13:02:10:333  shouldCollectReportForDate 2016-12-18 00:00:00 +0000 result: YES.
```

I've signed out and back in again with same credentials that worked before but it just doesn't update.

**Comment by caioaugusto1998** [comment]
I WANT A NEW ATMOSPHERE ON STAR ATLAS WE ALL WANT PAUL

**Comment by ferreiradantas7** [comment]
you can help me no
